title: Andross
description: There are no such thing as a sad unicorn.

client:
  market:
  name:
  brand: '#'
  brokerage: '#'
  address:
  phone:
  email:
  url:
  # if forms put '/homevalue/' or '/homesearch/'
  homeeval: http://hello.com
  homeeval_txt: Home Evaluation
  homesearch: http://hello.com
  homesearch_txt: Home Search
  VR_form:

# social links
socials:
  facebook: 'http://facebook.com'
  linkedin: 'http://linked.com'
  gplus: 'http://plus.google.com'
  youtube: 'http://youtube.com'
  twitter: 'http://twitter.com'
  instagram: '#'
  pinterest: '#'
  zillow: 'http://#.com'
  trulia: 'http://#.com'
  yelp: 'http://#.com'
  podcast: 'http://#.com'

#podcast settings
podcast:
  # Something Real Estate Podcast
  title:
  categories:
    - category: 'News &amp; Politics'
  image:
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- market -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from --client brand-- - your professional --market-- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in San Francisco, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author:

#layout options
# if we want review buttons --
review_sm_icons: false
audit_header: false

#image settings
images:
  hero_image_path: http://0.design-milk.com/images/2015/12/iso_rynth03-pattern.jpg
  hero_logo_path: http://design.ubuntu.com/wp-content/uploads/logo-ubuntu_st_no%C2%AE-white-hex.png
  hero_background_hex: "#123456"
  client_headshot_path:

#colors
brand_hex: "#123456"
fontcolor_hex: "#353535"
